Repository remotestorage/remotestorage.js, pull requests merged in 2021-03, with the labels that each got.

#1227 Fix/improve bash snippet formatting
  doc/contributing/building.rst
  doc/contributing/docs.rst
  doc/contributing/release-checklist.rst
  doc/contributing/testing.rst
  doc/getting-started/how-to-add.rst
Labels: docs, improvement

#1225 Remove Travis CI and update docs for GitHub Actions
  .github/workflows/test-and-lint.yml
  .travis.yml
  README.md
  doc/contributing/testing.rst
Labels: dev environment

#1231 Remove Bower package support
  bower.json
  doc/contributing/release-checklist.rst
  doc/getting-started/how-to-add.rst
  package.json
  scripts/update-bower-version.sh
Labels: dev environment

#1232 Don't include unnecessary files in npm package
  .gitignore
  .hound-js-style.json
  .hound.yml
  .npmignore
Labels: dev environment, improvement

#1233 Document usage with TypeScript
  doc/index.rst
  doc/typescript.rst
Labels: docs
